### PR TITLE
Added load more button 

### PR DESCRIPTION
**Pull request by adyz**
Hello!

Awesome stuff with this component guys!

We needed to use this component on another page that needed a "load more" button for the first time the user enters the page and after the first click on the "load more" button, to load on scroll as this component is intended.

After some thoughts I imagined that in the future maybe in some pages we will want the "load more" button always.

An so, I added a new property called `loadbutton` that accepts two strings: `once` or `always` and defaults to `never`.

```
<infinite-loading :on-infinite="onInfinite" :distance="distance" loadbutton="once" ref="infiniteLoading"></infinite-loading>
```

I managed to make the tests pass, but not sure if this is the best approach.

Can you please take a look and let me know if there are things that you would do better to make this pull request acceptable?

Also, do you think that this is a good feature and should update the docs too?

Thank you!

### CODE REVIEW

**Comment by syn-zeta** [comment]
Can you please create a [fiddle](https://jsfiddle.net/) demonstrating what this accomplishes (or what your requirements are -- it is not very clear from your description to me)? I think that this is something that can be more easily implemented outside of this component.

**Comment by adyz** [comment]
https://jsfiddle.net/adyz/81961uxv/3/


On the `infinite-loading` component you can add `loadbutton` and one of the two options `once` or `always` 

```

**Comment by adyz** [comment]
Here is an example with a styled button: https://jsfiddle.net/adyz/81961uxv/8/

**Comment by syn-zeta** [comment]
Here's an implementation for "load more" very close to yours with v2.1.3: https://jsfiddle.net/21g39g3p/ (the `distance` can be updated to a positive # after first click on "load more" button).

Another way would be to have a way to trigger a hard reset without taking into account the distance which will sync the component spinner as well. I think this may be something that would have been solved if #56 was addressed.

**Comment by adyz** [comment]
Thank you for your time, will close the pull request and I'll use my branch in the projects I need the load more.

**Pull request closed without merging**
