### PR TITLE
add name attribute to InfiniteLoading component

### PR DESCRIPTION
**Pull request by rquelen**
Hello,

Using vue-test-utils, we need the **name** attribute to be set on the component if we want to find it in the template.

For example : 
```
it('should contain infinite loading component', () => {
      // when
      const wrapper = shallow(LatestNews);

      // then
      const infiniteLoadingComponents = wrapper.findAll(InfiniteLoading);
      expect(infiniteLoadingComponents.length).toEqual(1);
});
```

Thank you

### CODE REVIEW

**Comment by PeachScript** [comment]
Nick work, thank you!

**Comment by damienbeaufils** [comment]
Thanks for the PR! 
@PeachScript I'm waiting for this feature too. Do you think it will be released soon?

**Comment by PeachScript** [comment]
@damienbeaufils got it, I will release a new version today :P

**Comment by damienbeaufils** [comment]
@PeachScript Thanks!

**Comment by PeachScript** [comment]
@damienbeaufils the new version [v2.2.2](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.2) has been released.

**Comment by damienbeaufils** [comment]
@PeachScript Awesome! But there is a little mistake on the release note: I’m not the contributor of this PR, it’s @rquelen ;)

**Comment by PeachScript** [comment]
@damienbeaufils oh it's my fault, thanks for your reminding!

And I'm sorry for this @rquelen , it has been corrected.

**Pull request merged**
