### PR TITLE
FireFox: getComputedStyle returns null for iFrame

### PR DESCRIPTION
**Pull request by vbabenko**
@PeachScript hey, Could you please take a look on this pull-request.
added check for `getScrollParent` method to define if `getComputedStyle` returns null.
Issue is reproducible for FireFox in case of iFrame
https://bugzilla.mozilla.org/show_bug.cgi?id=548397

### CODE REVIEW

**Comment by PeachScript** [comment]
Thanks @vbabenko , but I think it is destructive, because it replace the `getComputedStyle` globally. How do you think this:
```js
...
else if (['scroll', 'auto'].indexOf((getComputedStyle(elm) || {}).overflowY) > -1) {
...
```

**Comment by vbabenko** [comment]
@PeachScript agree, it's much better. I've tested it as well on FF and it works. I've updated pull request. You can merge or update by yourself. I am currently sitting on fork and will wait when I can switch back to your master)

**Comment by PeachScript** [comment]
@vbabenko thanks again! And I have other questions about this PR, please tell me if you have any idea:

1. What kind of situation will use a iframe with `display: none` and use infinite scroll component at the same time?
2. How can we test this change in unit test?

**Comment by PeachScript** [comment]
No updates, I will close it.

**Comment by vbabenko** [comment]
Hey @PeachScript 
Sorry for this delay...

I will try to answer on your questions:
`What kind of situation will use a iframe with display: none and use infinite scroll component at the same time?`
- I am using KeenUi Modal that contains iframe with huge list of items. When page is rendered Modal component initialized and infiniteScrolling is triggered (but modal actually is closed). And in this situation infinite loading throws exception for FireFox browser due to their issue `getComputedStyle` returns null for iframe

`How can we test this change in unit test?`
- I do not know how to cover via unit tests and if any sense in this

Thanks, I and sorry for delay

**Comment by PeachScript** [comment]
@vbabenko thanks for your explanation! Sorry forgot to reply your comment.

In order to understand this issue expediently for others, I will reply your comment in your issue.

**Pull request closed without merging**
